name: Live cache

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  cache-warm:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get install chromium-browser
      - name: Fetch
        run: chromium-browser --headless https://insights.threesixtygiving.org/ && sleep 30
